import React, { useState, useEffect, useMemo } from "react";
import { Loader2, Search, X } from "lucide-react";
import { fetchOracleTexts } from "../../lib/scryfall";
import { C, STOCK_BG, STOCK_SHADOW } from "../../lib/tokens";

export const KEYWORD_GUIDE = [
  { k: "Flying", re: /\bflying\b/, d: "This creature can only be blocked by creatures with flying or reach. It sails over everything else." },
  { k: "First strike", re: /\bfirst strike\b/, d: "Deals its combat damage before creatures without it. If it kills the blocker first, it takes nothing back." },
  { k: "Double strike", re: /\bdouble strike\b/, d: "Deals combat damage twice — once with first strikers, then again with everyone else." },
  { k: "Deathtouch", re: /\bdeathtouch\b/, d: "Any amount of damage this deals to a creature is enough to destroy it. Even 1 damage kills." },
  { k: "Defender", re: /\bdefender\b/, d: "Can block, but can't attack. Walls and gates have this." },
  { k: "Flash", re: /\bflash\b/, d: "You can cast this at any time you could cast an instant — including in the middle of combat or on your opponent's turn." },
  { k: "Haste", re: /\bhaste\b/, d: "Can attack and use tap abilities the turn it comes down, skipping the usual one-turn wait ('summoning sickness')." },
  { k: "Hexproof", re: /\bhexproof\b/, d: "Your opponents can't target it with spells or abilities. You still can." },
  { k: "Indestructible", re: /\bindestructible\b/, d: "Ignores 'destroy' effects and lethal damage. Can still be exiled, sacrificed, or shrunk to 0 toughness." },
  { k: "Lifelink", re: /\blifelink\b/, d: "Damage this deals also gains you that much life, simultaneously." },
  { k: "Menace", re: /\bmenace\b/, d: "Can't be blocked by just one creature — your opponent must commit two or more blockers." },
  { k: "Protection", re: /\bprotection from\b/, d: "Protection from X means it can't be damaged, enchanted, equipped, blocked, or targeted by anything X. Remember it as DEBT: Damaged, Enchanted, Blocked, Targeted." },
  { k: "Reach", re: /\breach\b/, d: "Can block creatures with flying, despite being grounded. Spiders, mostly." },
  { k: "Trample", re: /\btrample\b/, d: "If it deals more combat damage than the blocker can absorb, the excess spills through to the defending player." },
  { k: "Vigilance", re: /\bvigilance\b/, d: "Doesn't tap when attacking, so it's still available to block on the way back." },
  { k: "Ward", re: /\bward\b/, d: "Ward N taxes your opponents: their spell or ability targeting this is countered unless they pay N extra." },

  { k: "Scry", re: /\bscry \d|\bscry x\b/, d: "Look at that many cards from the top of your library; put any of them on the bottom and the rest back on top in any order. Quality control for your next draws." },
  { k: "Surveil", re: /\bsurveil \d/, d: "Like scry, but rejected cards go to your graveyard instead of the bottom — which some decks actively want." },
  { k: "Sacrifice", re: /\bsacrifice\b/, d: "Put your own permanent into the graveyard as a cost or effect. Sacrificed things can't be saved by indestructible, and only you can sacrifice your own permanents." },
  { k: "Exile", re: /\bexile\b/, d: "Removed from the game entirely — a zone outside the graveyard where most things can't be retrieved. The cleanest removal." },
  { k: "Mill", re: /\bmill(s|ed)? \d|\bmill(s|ed)? x\b/, d: "Put that many cards from the top of a library straight into the graveyard. A win condition for some, fuel for graveyard decks." },
  { k: "Counterspells", re: /counter target .*(spell|abilit)/, d: "Cancel a spell while it's still being cast — it goes to the graveyard and never happens. Only works while the spell is on the stack." },
  { k: "Fight", re: /\bfights?\b/, d: "Two creatures deal damage equal to their power to each other simultaneously. Neither is 'combat' damage, so first strike doesn't apply." },
  { k: "Proliferate", re: /\bproliferate\b/, d: "Choose any number of permanents and players with counters on them; give each one more of each kind of counter they already have." },
  { k: "Goad", re: /\bgoad(s|ed)?\b/, d: "A goaded creature must attack someone other than you next turn if able. Multiplayer chaos fuel." },
  { k: "Tap / Untap", re: /\{t\}|untap(s|ped)?/, d: "Tapping (turning sideways) marks a card as used — for attacking, mana, or abilities. Untapping at the start of your turn resets it." },

  { k: "+1/+1 counters", re: /\+1\/\+1 counter/, d: "Physical markers that permanently grow a creature by one power and one toughness each. They stay through anything short of the creature leaving the battlefield." },
  { k: "Tokens", re: /create.*token/, d: "Creature (or other) cards generated by an effect rather than cast from your hand. They vanish for good if they ever leave the battlefield." },
  { k: "Treasure", re: /\btreasure\b/, d: "An artifact token you can sacrifice for one mana of any color. Banked mana with a shovel." },
  { k: "Food", re: /\bfood\b.*token|sacrifice.*food/, d: "An artifact token: pay 2 and sacrifice it to gain 3 life." },
  { k: "Clue", re: /\bclue\b|investigate/, d: "An artifact token from 'investigate': pay 2 and sacrifice it to draw a card." },
  { k: "Equipment", re: /\bequip\b/, d: "An artifact you attach to a creature for its equip cost. The gear stays on the battlefield when the wearer dies and can be re-equipped." },
  { k: "Auras", re: /\benchant creature\b|\benchant permanent\b|\benchant land\b/, d: "Enchantments attached to something. Unlike equipment, an aura goes to the graveyard if the thing it enchants leaves." },

  { k: "Landfall", re: /\blandfall\b/, d: "An ability word: something happens every time a land enters the battlefield under your control. Rewarded for simply playing lands — and doubly for fetching extras." },
  { k: "Prowess", re: /\bprowess\b/, d: "Gets +1/+1 until end of turn whenever you cast a noncreature spell. Spellslinger decks stack these triggers fast." },
  { k: "Cascade", re: /\bcascade\b/, d: "When you cast this, exile cards from the top of your library until you hit a cheaper nonland spell — then cast that one for free." },
  { k: "Flashback", re: /\bflashback\b/, d: "A spell you can cast a second time from your graveyard for its flashback cost, then it exiles itself." },
  { k: "Kicker", re: /\bkick(er|ed)\b/, d: "An optional extra cost. Pay it when casting and the spell does something bigger." },
  { k: "Monarch", re: /\bmonarch\b/, d: "A title one player holds: draw an extra card at your end step. Dealing combat damage to the monarch steals the crown." },
  { k: "Partner", re: /\bpartner\b/, d: "Commander mechanic: two legends with partner can share the command zone as co-commanders." },
  { k: "Devotion", re: /\bdevotion\b/, d: "Counts the colored mana symbols among permanents you control. More committed to a color, bigger the payoff." },
  { k: "The Ring tempts you", re: /the ring tempts you/, d: "A Lord of the Rings mechanic: each temptation upgrades your Ring's powers and picks a Ring-bearer creature that gets progressively harder to block and more dangerous." },

  // ---- expanded batch: commonly missed keywords from the last decade or so of sets ----
  { k: "Convoke", re: /\bconvoke\b/, d: "You can tap untapped creatures you control to help cast this spell — each one pays for one generic mana, or one mana of its own color." },
  { k: "Delve", re: /\bdelve\b/, d: "You can exile cards from your graveyard to help pay this spell's generic mana cost, one card per generic mana." },
  { k: "Escape", re: /\bescape\b/, d: "You can cast this from your graveyard by paying its escape cost, which includes exiling a number of other cards from your graveyard." },
  { k: "Mutate", re: /\bmutate\b/, d: "Cast this onto a non-Human creature you own instead of the battlefield. The two merge into one creature with all abilities, using whichever card's stats are on top." },
  { k: "Foretell", re: /\bforetell\b/, d: "During your turn, you can pay {2} and exile this from your hand face down. Later, cast it for its (usually cheaper) foretell cost." },
  { k: "Disturb", re: /\bdisturb\b/, d: "You can cast this from your graveyard as its (usually different) back face, typically an Aura or lesser version, for its disturb cost." },
  { k: "Blitz", re: /\bblitz\b/, d: "Cast a creature for its blitz cost and it gains haste, plus you draw a card when it dies — but it's sacrificed at the next end step." },
  { k: "Backup", re: /\bbackup\b/, d: "This creature enters and gives +1/+1 counters and some of its own abilities to itself and/or another target creature for the turn." },
  { k: "Bargain", re: /\bbargain\b/, d: "You can sacrifice an artifact, enchantment, or token as you cast this for an extra effect or discount." },
  { k: "Offspring", re: /\boffspring\b/, d: "Pay the offspring cost as you cast this creature to also create a 1/1 copy of it." },
  { k: "Impending", re: /\bimpending\b/, d: "Cast for its impending cost, it enters as a non-creature enchantment with a countdown; once the counters run out it becomes a creature." },
  { k: "Discover", re: /\bdiscover \d/, d: "Exile cards from the top of your library until you hit a nonland card costing less than the discover value, then cast it free or put it in hand." },
  { k: "Boast", re: /\bboast\b/, d: "An ability you can activate only if this creature attacked this turn." },
  { k: "Blood token", re: /blood token/, d: "An artifact token: pay 1 and discard a card to draw a card. A slower, card-filtering cousin of Clue and Treasure." },
  { k: "Role token", re: /role token/, d: "An Aura token that attaches to a creature and grants it a small, fixed bonus (like +1/+1 or flying) depending on which role it is." },
  { k: "Manifest", re: /\bmanifest(s|ed)?\b/, d: "Put the top card of your library onto the battlefield face down as a 2/2 creature. It can be turned face up later if it's a creature card." },
  { k: "Storm", re: /\bstorm\b/, d: "When you cast this, copy it once for each other spell cast earlier this turn. Can produce a huge number of copies in the right deck." },
  { k: "Affinity", re: /\baffinity for\b/, d: "This spell costs {1} less to cast for each permanent you control matching the stated type (usually artifacts)." },
  { k: "Explore", re: /\bexplores?\b/, d: "Reveal the top card of your library. Put it in hand if it's a land; otherwise put a +1/+1 counter on the exploring creature and choose whether to keep the card on top or bin it." },
  { k: "Amass", re: /\bamass\b/, d: "Put counters on an Army creature you control, creating a 0/0 Army token first if you don't have one." },
  { k: "Jump-start", re: /jump-start/, d: "Cast this from your graveyard by discarding a card in addition to its normal cost, then it's exiled instead of returning to the graveyard." },
  { k: "Unearth", re: /\bunearth\b/, d: "Pay the unearth cost to return this creature from your graveyard to the battlefield with haste — but it's exiled if it would leave the battlefield, or at the next end step." },
  { k: "Persist", re: /\bpersist\b/, d: "When this dies, if it had no -1/-1 counters on it, return it to the battlefield with a -1/-1 counter." },
  { k: "Wither", re: /\bwither\b/, d: "This deals damage to creatures in the form of -1/-1 counters instead of regular damage, which doesn't heal at end of turn." },
  { k: "Infect", re: /\binfect\b/, d: "This deals damage to creatures as -1/-1 counters and to players as poison counters instead of life loss. Ten poison counters is a loss." },
  { k: "Connive", re: /\bconnives?\b/, d: "Draw a card, then discard a card. If you discarded a nonland card this way, put a +1/+1 counter on the connived creature." },
  { k: "Ninjutsu", re: /\bninjutsu\b/, d: "Return an unblocked attacker you control to hand to put this creature from hand onto the battlefield attacking in its place." },
  { k: "Cycling", re: /\bcycling\b/, d: "Pay the cycling cost and discard this card from your hand to draw a new card — a way to turn a dead draw into a fresh one." },
  { k: "Morph", re: /\bmorph\b/, d: "You can cast this face down as a vanilla 2/2 for {3}, then later pay its morph cost to turn it face up." },
  { k: "Bestow", re: /\bbestow\b/, d: "Cast this for its bestow cost to have it enter as an Aura enchanting a creature instead of a creature itself, granting its stats and abilities." },
  { k: "Embalm / Eternalize", re: /\b(embalm|eternalize)\b/, d: "Exile this card from your graveyard to create a token copy of it (embalm makes it the printed size; eternalize makes it a 4/4)." },
  { k: "Enlist", re: /\benlist\b/, d: "As this attacks, you can tap an untapped non-attacking creature to add its power to this one's for combat." },
  { k: "Casualty", re: /\bcasualty\b/, d: "You can sacrifice a creature with the stated power or greater as you cast this to copy the spell." },
  { k: "Alliance", re: /\balliance\b/, d: "An ability word: triggers whenever another creature enters the battlefield under your control." },

  // ---- second batch: more genuinely common gaps, including Assassin's Creed's own signature mechanic ----
  { k: "Freerunning", re: /\bfreerunning\b/, d: "Cast this for its (usually cheaper) freerunning cost if you attacked with a Rogue or Assassin this turn — Assassin's Creed's signature mechanic." },
  { k: "Fabricate", re: /\bfabricate\b/, d: "Choose one as this enters: put that many +1/+1 counters on it, or create that many 1/1 Servo artifact creature tokens." },
  { k: "Improvise", re: /\bimprovise\b/, d: "You can tap untapped artifacts you control to help cast this spell, the same way convoke uses creatures." },
  { k: "Constellation", re: /\bconstellation\b/, d: "An ability word: triggers whenever an enchantment enters the battlefield under your control (including this one)." },
  { k: "Ferocious", re: /\bferocious\b/, d: "An ability word: this gets better if you control a creature with power 4 or greater." },
  { k: "Raid", re: /\braid\b/, d: "An ability word: this gets better if you attacked with a creature this turn." },
  { k: "Formidable", re: /\bformidable\b/, d: "An ability word: this gets better if creatures you control have total power 8 or greater." },
  { k: "Awaken", re: /\bawaken\b/, d: "Pay the awaken cost to also turn a land you control into an X/X creature with +1/+1 counters, in addition to the spell's normal effect." },
  { k: "Monstrosity", re: /\bmonstrosity\b/, d: "Pay the cost (once per game) to put that many +1/+1 counters on this and make it 'monstrous', which some cards care about." },
  { k: "Heroic", re: /\bheroic\b/, d: "Triggers whenever you cast a spell that targets this creature." },
  { k: "Bloodthirst", re: /\bbloodthirst\b/, d: "This enters with the stated +1/+1 counters if an opponent lost life this turn." },
  { k: "Extort", re: /\bextort\b/, d: "Whenever you cast a spell, you may pay {W/B} to make each opponent lose 1 life and you gain that much life." },
  { k: "Proliferate", re: /\bproliferate\b/, d: "Choose any number of permanents and/or players with a counter on them, then give each one more of each kind of counter it already has." },
  { k: "Populate", re: /\bpopulate\b/, d: "Create a token copy of a creature token you control — a way to duplicate your best token." },
  { k: "Investigate", re: /\binvestigates?\b/, d: "Create a Clue artifact token: pay {2} and sacrifice it to draw a card, whenever you want." },
  { k: "Champion", re: /\bchampion\b/, d: "When this enters, exile another permanent you control of the stated type; when this leaves, return the exiled card." },
  { k: "Rebound", re: /\brebound\b/, d: "If you cast this from hand, exile it as it resolves instead of putting it in the graveyard — you may cast it again from exile for free on your next turn." },
  { k: "Miracle", re: /\bmiracle\b/, d: "If this is the first card you drew this turn, you may reveal it to cast it for its (usually much cheaper) miracle cost." },
  { k: "Overload", re: /\boverload\b/, d: "Pay the overload cost to change 'target' to 'each' — the spell now affects everything it could normally target, all at once." },
  { k: "Detain", re: /\bdetain(s|ed)?\b/, d: "The permanent can't attack, block, or have its activated abilities used until your next turn." },
  { k: "Cipher", re: /\bcipher\b/, d: "You may exile this spell encoded on a creature as it resolves; whenever that creature deals combat damage, you may cast a copy of this spell for free." },
  { k: "Evolve", re: /\bevolves?\b/, d: "Whenever a creature enters under your control with greater power or toughness than this one, put a +1/+1 counter on this." },
  { k: "Outlast", re: /\boutlast\b/, d: "Pay the outlast cost and tap this (only as a sorcery) to put a +1/+1 counter on it." },
  { k: "Dethrone", re: /\bdethrone\b/, d: "Whenever this attacks the player with the most life (or tied for most), put a +1/+1 counter on it." },
  { k: "Meld", re: /\bmeld\b/, d: "Two specific cards you own can combine into one bigger, transformed card when both are on the battlefield under your control." },
  { k: "Partner", re: /\bpartner\b/, d: "You can have two commanders instead of one, as long as both have partner (or are specifically named as each other's partner)." },
  { k: "Devotion", re: /\bdevotion to\b/, d: "A count of the colored mana symbols in the mana costs of your permanents of that color — several cards scale with it." },
  { k: "Kicker", re: /\bkicker\b/, d: "Pay the kicker cost in addition to the normal cost as you cast this for an extra effect." },
  { k: "Entwine", re: /\bentwine\b/, d: "Pay the entwine cost to choose all of a modal spell's options instead of just one." },
  { k: "Replicate", re: /\breplicate\b/, d: "Pay the replicate cost any number of times as you cast this to create that many extra copies, each needing a legal target." },
  { k: "Madness", re: /\bmadness\b/, d: "If you'd discard this card, you may cast it for its madness cost instead, or put it in the graveyard as normal." },
  { k: "Threshold", re: /\bthreshold\b/, d: "An ability word: this gets better if you have seven or more cards in your graveyard." },
  { k: "Delirium", re: /\bdelirium\b/, d: "An ability word: this gets better if your graveyard has four or more different card types in it." },
  { k: "Riot", re: /\briot\b/, d: "Choose as this enters: a +1/+1 counter, or haste." },
  { k: "Spectacle", re: /\bspectacle\b/, d: "Cast this for its (usually cheaper) spectacle cost if an opponent lost life this turn." },
  { k: "Addendum", re: /\baddendum\b/, d: "An ability word: this gets better if you cast it during your main phase, before combat." },
];

/* ============================================================
   LIFE COUNTER — live game tracker (Commander / Normal)
   ============================================================ */

export function computeGlossarySearchDiagnostic(query, entries, withText, oracle) {
  const q = query.trim().toLowerCase();
  if (!q || entries.length > 0) return null;
  const known = KEYWORD_GUIDE.some((kw) => kw.k.toLowerCase().includes(q));
  const cardsWithText = withText.filter((c) => {
    const text = (oracle[c.scryfallId]?.t || "").toLowerCase();
    return text.includes(q);
  });
  if (cardsWithText.length > 0) {
    return {
      tone: "bug",
      text: `${cardsWithText.length} of your scanned card${cardsWithText.length === 1 ? "" : "s"} (${cardsWithText
        .slice(0, 3)
        .map((c) => c.name)
        .join(", ")}${cardsWithText.length > 3 ? ", …" : ""}) actually mention "${query.trim()}" in their rules text — this looks like a real gap in the glossary, worth reporting.`,
    };
  }
  if (!known) {
    return {
      tone: "unknown",
      text: `"${query.trim()}" isn't a mechanic name the glossary recognizes yet.`,
    };
  }
  return {
    tone: "not-owned",
    text: `None of your ${withText.length} scanned cards mention "${query.trim()}" in their rules text — you likely don't own a card with this mechanic (yet).`,
  };
}

export function GlossaryView({ cards }) {
  // Reads and writes through the exact same cache fetchOracleTexts uses
  // (localStorage key "lf-oracle-v2") — this used to read from a different,
  // stale key ("lf-oracle-cache") that nothing ever wrote to, so every scan
  // appeared to vanish on the next visit even though the real cache was
  // sitting there correctly the whole time.
  const [oracle, setOracle] = useState({});
  const [scanning, setScanning] = useState(false);
  const [query, setQuery] = useState("");

  const owned = useMemo(() => cards.filter((c) => !c.sold), [cards]);
  const withText = useMemo(
    () => owned.filter((c) => c.scryfallId && oracle[c.scryfallId]),
    [owned, oracle]
  );

  async function scan() {
    setScanning(true);
    try {
      const map = await fetchOracleTexts(owned.filter((c) => c.scryfallId).map((c) => c.scryfallId));
      setOracle({ ...map });
    } catch (e) {}
    setScanning(false);
  }

  // Load automatically on mount/whenever the collection changes — cards
  // already in the cache resolve instantly with no network call at all, so
  // this only ever costs something real for genuinely new cards. No more
  // needing to remember to press Scan just to see what you already scanned.
  useEffect(() => {
    let live = true;
    const ids = owned.filter((c) => c.scryfallId).map((c) => c.scryfallId);
    if (ids.length === 0) return;
    fetchOracleTexts(ids)
      .then((map) => {
        if (live) setOracle((prev) => ({ ...prev, ...map }));
      })
      .catch(() => {});
    return () => {
      live = false;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [owned.map((c) => c.scryfallId).join(",")]);

  const entries = useMemo(() => {
    return KEYWORD_GUIDE.map((kw) => {
      const matches = [];
      withText.forEach((c) => {
        const text = ((oracle[c.scryfallId]?.t || "") + " " + (c.typeLine || "")).toLowerCase();
        if (kw.re.test(text)) matches.push(c.name);
      });
      const unique = [...new Set(matches)];
      return { ...kw, count: unique.length, examples: unique.slice(0, 3) };
    })
      .filter((e) => e.count > 0)
      .filter((e) => !query || e.k.toLowerCase().includes(query.toLowerCase()))
      .sort((a, b) => b.count - a.count);
  }, [withText, oracle, query]);

  // When a search comes up empty, tell the person WHY rather than leaving
  // them to guess whether it's a bug or they just don't own such a card.
  // Checks the raw scanned text directly, bypassing the keyword list
  // entirely, so it answers the question honestly either way.
  const searchDiagnostic = useMemo(
    () => computeGlossarySearchDiagnostic(query, entries, withText, oracle),
    [query, entries, withText, oracle]
  );

  const unscanned = owned.filter((c) => c.scryfallId && !oracle[c.scryfallId]).length;

  return (
    <main style={{ padding: "16px clamp(14px, 4vw, 30px) 48px" }}>
      <div style={{ display: "flex", alignItems: "center", gap: 14, flexWrap: "wrap", marginBottom: 20 }}>
        <div className="serif" style={{ fontSize: 16, fontWeight: 600, color: C.goldBright }}>
          Keywords on your cards
        </div>
        <span className="mono" style={{ fontSize: 10.5, color: C.parchmentDim }}>
          {entries.length} mechanics found across {withText.length} scanned cards
        </span>
        <div style={{ flex: 1 }} />
        <input
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="Find a keyword…"
          aria-label="Find a keyword"
          style={{
            background: C.bgPanel2,
            border: `1px solid ${C.border}`,
            borderRadius: 6,
            padding: "8px 11px",
            color: C.parchment,
            fontSize: 13,
            width: 170,
          }}
        />
        {unscanned > 0 && (
          <button
            onClick={scan}
            disabled={scanning}
            style={{
              display: "flex",
              alignItems: "center",
              gap: 7,
              background: STOCK_BG,
              color: C.stockInk,
              border: "none",
              borderRadius: 5,
              padding: "8px 14px",
              fontWeight: 700,
              fontSize: 12.5,
              cursor: scanning ? "default" : "pointer",
              boxShadow: STOCK_SHADOW,
            }}
          >
            {scanning ? <Loader2 size={14} style={{ animation: "spin 1s linear infinite" }} /> : <Search size={14} />}
            Scan {unscanned} unread cards
          </button>
        )}
      </div>

      {withText.length === 0 && !scanning && (
        <div
          style={{
            border: `1px dashed rgba(185,191,199,0.3)`,
            borderRadius: 10,
            padding: 30,
            maxWidth: 560,
            color: C.parchmentDim,
            fontSize: 13.5,
            lineHeight: 1.6,
          }}
        >
          The glossary reads your cards' rules text to find which mechanics actually appear in your
          collection — it loads automatically and stays cached, so this only takes a moment the
          first time. New cards get picked up the next time you open this tab, or press{" "}
          <b style={{ color: C.parchment }}>Scan</b> to fetch them right away.
        </div>
      )}

      {searchDiagnostic && (
        <div
          style={{
            border: `1px solid ${searchDiagnostic.tone === "bug" ? "rgba(222,115,134,0.4)" : C.border}`,
            borderRadius: 10,
            padding: "14px 18px",
            marginBottom: 20,
            color: searchDiagnostic.tone === "bug" ? C.redBright : C.parchmentDim,
            fontSize: 13,
            lineHeight: 1.6,
          }}
        >
          {searchDiagnostic.text}
        </div>
      )}

      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))", gap: 16 }}>
        {entries.map((e) => (
          <div
            key={e.k}
            style={{
              background: "rgba(255,255,255,0.045)",
              border: `1px solid rgba(185,191,199,0.18)`,
              borderRadius: 10,
              padding: "14px 16px",
            }}
          >
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", gap: 10, marginBottom: 9 }}>
              <span
                className="mono"
                style={{
                  fontSize: 10,
                  letterSpacing: 1.4,
                  textTransform: "uppercase",
                  background: STOCK_BG,
                  color: C.stockInk,
                  fontWeight: 600,
                  padding: "4px 10px",
                  borderRadius: 3,
                  boxShadow: STOCK_SHADOW,
                }}
              >
                {e.k}
              </span>
              <span className="mono" style={{ fontSize: 10.5, color: C.parchmentDim, flexShrink: 0 }}>
                {e.count} card{e.count === 1 ? "" : "s"}
              </span>
            </div>
            <div style={{ fontSize: 13, lineHeight: 1.6, color: C.parchment }}>{e.d}</div>
            {e.examples.length > 0 && (
              <div className="serif" style={{ fontSize: 12, color: C.parchmentDim, marginTop: 9, fontStyle: "italic" }}>
                e.g. {e.examples.join(" · ")}
                {e.count > e.examples.length ? ` +${e.count - e.examples.length} more` : ""}
              </div>
            )}
          </div>
        ))}
      </div>
    </main>
  );
}

/* ============================================================
   DECK LISTS — import and export
   ============================================================ */

